Homework
Technolords/microservice-mock pull request #30
Opened 2016-11-23 20:12 UTC by SrideviJava

New Origin/Homework created, containing the fix to the StatsCommandTest and StopCommandTest.

2016-11-23 20:41 UTC, Technolords requested changes

2016-11-23 20:41 UTC, Technolords commented on pom.xml
> +        <dependency>
Do we need this dependency?

2016-11-23 20:41 UTC, Technolords commented on src/test/java/net/technolords/micro/RouteTestSupport.java
> +public class RouteTestSupport extends CamelTestSupport{
Test if we can do without CamelTestSupport, as it adds nothing?

2016-11-23 20:41 UTC, Technolords commented on src/test/java/net/technolords/micro/command/StatsCommandTest.java
>      private String availablePort;
Move the part and logic of available port into the parent class (i.e. TestSupport)

2016-11-23 20:41 UTC, Technolords commented on src/test/java/net/technolords/micro/command/StatsCommandTest.java
> +    public void testStatsCommand2() throws Exception{
This method is now a duplicate after the merge.

2016-12-04 21:48 UTC, SrideviJava commented on pom.xml
> +        <dependency>
Removed the Dependency.

2016-12-04 21:49 UTC, SrideviJava commented on src/test/java/net/technolords/micro/RouteTestSupport.java
> +public class RouteTestSupport extends CamelTestSupport{
CamelTestSupport is removed as it adds no added value.

2016-12-04 21:52 UTC, SrideviJava commented on src/test/java/net/technolords/micro/command/StatsCommandTest.java
>      private String availablePort;
While trying to move the logic of available port and setUp to Class Route Test Support, I get NPE. I see in debug mode, my reference object value is null. Test Class is extending RouteTestSupport, but in debug I see TestClassObject reference is not receiving the values from Parent Class.

2016-12-06 22:10 UTC, SrideviJava commented on src/test/java/net/technolords/micro/command/StatsCommandTest.java
>      private String availablePort;
done, push is pending.

2016-12-06 22:11 UTC, SrideviJava commented on src/test/java/net/technolords/micro/command/StatsCommandTest.java
> +    public void testStatsCommand2() throws Exception{
done.

2016-12-07 20:41 UTC, Technolords commented
After review together, it appears that from full build, the beforeSuite/Test breaks the build, as the stopCommand stops the context and the subsequent test cannot use that same context...

suggestions:
- isolate the stop with its own context
- change the order of the tests when they are executed
- refactor testSupport in a factory, where each test gets its own context (but the wiring etc is done/shared in one place)

The last suggestion has my preference

2016-12-07 20:44 UTC, Technolords commented on src/test/java/net/technolords/micro/RouteTestSupport.java
>  public class RouteTestSupport extends CamelTestSupport{
CamelTestSupport is not needed, as it adds nothing

2016-12-08 07:43 UTC, Technolords commented
Had to try something this morning... namely to change BeforeSuite or BeforeTest into BeforeClass and that worked! Later today I will push my changes and merge it. Consider homework done!

2016-12-08 08:02 UTC, merged